import type { ProcedureDefinition } from './types';

const timestamp = '2026-08-16T00:00:00.000Z';

export const SONIC_PROCEDURE_CATALOG: readonly ProcedureDefinition[] = [
  {
    id: 'sonic-verifone-device-swap',
    customerKey: 'sonic',
    name: 'Sonic Verifone Device Swap',
    description: 'Verifone V400M and UX301/UX401 field service replacement procedure for Sonic drive-in locations.',
    version: '1.0.0',
    status: 'active',
    category: 'technician',
    jobType: 'field_task',
    createdAt: timestamp,
    updatedAt: timestamp,
    steps: [
      // ========== 1. Preparation ==========
      {
        id: 'prep-identify-devices',
        phaseId: 'preparation',
        phaseLabel: 'Preparation',
        title: 'Identify devices being serviced',
        guidedInstructions:
          'Review the work order and identify every device being serviced at this site: V400M terminal, UX301 display, and/or UX401 display. Confirm the replacement units are on-hand before starting.',
        quickCheckpoint: 'Identify all devices being serviced and confirm replacements on-hand.',
        classification: 'required',
        displayOrder: 10,
      },
      {
        id: 'prep-parts-tools',
        phaseId: 'preparation',
        phaseLabel: 'Preparation',
        title: 'Identify required parts and tools',
        guidedInstructions:
          'Gather every part, cable, and tool listed on the work order. Common items include the replacement device, power cables, data cables, and any mounting hardware. Do not start until all required parts are present.',
        quickCheckpoint: 'Confirm all required parts and tools are present.',
        classification: 'required',
        displayOrder: 11,
      },
      {
        id: 'prep-tamper-labels',
        phaseId: 'preparation',
        phaseLabel: 'Preparation',
        title: 'Verify tamper labels are intact',
        guidedInstructions:
          'Where the work order calls for tamper verification, inspect tamper-evident labels on the existing device and surrounding enclosure. Document any broken or missing labels before proceeding.',
        quickCheckpoint: 'Tamper labels verified intact.',
        classification: 'conditional',
        condition: { type: 'job_field_equals', field: 'notes', value: 'tamper-check' },
        displayOrder: 12,
        proofRequirements: [
          {
            id: 'prep-tamper-photo',
            label: 'Tamper label photo',
            proofType: 'photo',
            classification: 'conditional',
            instructions: 'Capture a clear photo of the tamper label status.',
            visitScope: 'any_visit',
            minimumCount: 1,
          },
        ],
      },
      {
        id: 'prep-lane-assignments',
        phaseId: 'preparation',
        phaseLabel: 'Preparation',
        title: 'Identify lane assignments',
        guidedInstructions:
          'Confirm which stall(s) / lane(s) are affected by this work order. Note the lane numbers and match them to the replacement devices to avoid cross-lane mix-ups.',
        quickCheckpoint: 'Lane assignments confirmed.',
        classification: 'required',
        displayOrder: 13,
      },
      {
        id: 'prep-usb-hub',
        phaseId: 'preparation',
        phaseLabel: 'Preparation',
        title: 'USB hub / USB drive when required',
        guidedInstructions:
          'If the work order specifies a USB hub or USB drive for software transfer or configuration, verify it is present and functional before starting.',
        quickCheckpoint: 'USB hub/drive present if required.',
        classification: 'conditional',
        condition: { type: 'job_field_equals', field: 'notes', value: 'usb-required' },
        displayOrder: 14,
      },
      {
        id: 'prep-wireless-input',
        phaseId: 'preparation',
        phaseLabel: 'Preparation',
        title: 'Wireless keyboard / mouse when required',
        guidedInstructions:
          'When the work order calls for Windows configuration or admin access, confirm a wireless keyboard and/or mouse is available for stall-side use.',
        quickCheckpoint: 'Wireless input devices present if required.',
        classification: 'conditional',
        condition: { type: 'job_field_equals', field: 'notes', value: 'wireless-input-required' },
        displayOrder: 15,
      },
      {
        id: 'prep-tools',
        phaseId: 'preparation',
        phaseLabel: 'Preparation',
        title: 'Confirm tools on-hand',
        guidedInstructions:
          'Ensure you have a Phillips screwdriver and any wrench or pliers noted on the work order before beginning physical work.',
        quickCheckpoint: 'Phillips screwdriver and required wrench/pliers on-hand.',
        classification: 'required',
        displayOrder: 16,
      },

      // ========== 2. Arrival / Check-In ==========
      {
        id: 'arrival-review-wo',
        phaseId: 'arrival',
        phaseLabel: 'Arrival / Check-In',
        title: 'Review work order / SAF',
        guidedInstructions:
          'Open the assigned work order and the Site Access Form (SAF). Read the scope, device list, and any special instructions before entering the work area.',
        quickCheckpoint: 'Work order and SAF reviewed.',
        classification: 'required',
        displayOrder: 20,
      },
      {
        id: 'arrival-greet-manager',
        phaseId: 'arrival',
        phaseLabel: 'Arrival / Check-In',
        title: 'Greet and coordinate with store manager',
        guidedInstructions:
          'Find the store manager on duty, introduce yourself, confirm the scheduled work, and ask if there are any site-specific restrictions or safety notes.',
        quickCheckpoint: 'Manager greeted and site conditions confirmed.',
        classification: 'required',
        displayOrder: 21,
      },
      {
        id: 'arrival-pop-key',
        phaseId: 'arrival',
        phaseLabel: 'Arrival / Check-In',
        title: 'Obtain POP stall key if necessary',
        guidedInstructions:
          'If the work area is behind a locked Point-of-Purchase enclosure, request the stall key from the manager before starting. Return it after work is complete.',
        quickCheckpoint: 'POP stall key obtained if needed.',
        classification: 'conditional',
        condition: { type: 'job_field_equals', field: 'notes', value: 'pop-key-required' },
        displayOrder: 22,
      },
      {
        id: 'arrival-verifone-support',
        phaseId: 'arrival',
        phaseLabel: 'Arrival / Check-In',
        title: 'Contact Verifone Help Desk when required',
        guidedInstructions:
          'When the work order states that Verifone support contact is required, reach out to the Help Desk before starting physical work. Provide the site name, work order number, and device type. Do not invent support credentials or phone numbers; use the contact details supplied on the work order.',
        quickCheckpoint: 'Verifone Help Desk contacted if work order requires it.',
        classification: 'conditional',
        condition: { type: 'job_field_equals', field: 'notes', value: 'verifone-support-required' },
        displayOrder: 23,
        supportEscalations: [
          {
            id: 'arrival-verifone-support-case',
            escalationLabel: 'Verifone Help Desk case reference',
            contactRoleType: 'technical_support',
            instructions: 'Contact Verifone Help Desk using the details provided on the work order. Provide site, work order, and device information.',
            referenceNumberRequired: true,
            conditional: true,
            condition: { type: 'job_field_equals', field: 'notes', value: 'verifone-support-required' },
          },
        ],
      },
      {
        id: 'arrival-verify-parts',
        phaseId: 'arrival',
        phaseLabel: 'Arrival / Check-In',
        title: 'Verify parts and cables before starting',
        guidedInstructions:
          'Lay out all replacement parts and cables next to the existing equipment. Compare each item to the work order line items. Do not start deinstallation until everything is accounted for.',
        quickCheckpoint: 'All parts and cables verified against work order.',
        classification: 'required',
        displayOrder: 24,
      },

      // ========== 3. Device Identification ==========
      {
        id: 'identify-v400m',
        phaseId: 'device-id',
        phaseLabel: 'Device Identification',
        title: 'V400M identified on job',
        guidedInstructions: 'Confirm the V400M terminal is listed on the work order and the replacement unit is present.',
        quickCheckpoint: 'V400M confirmed on work order.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'V400M' },
        displayOrder: 30,
      },
      {
        id: 'identify-ux301',
        phaseId: 'device-id',
        phaseLabel: 'Device Identification',
        title: 'UX301 identified on job',
        guidedInstructions: 'Confirm the UX301 display is listed on the work order and the replacement unit is present.',
        quickCheckpoint: 'UX301 confirmed on work order.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        displayOrder: 31,
      },
      {
        id: 'identify-ux401',
        phaseId: 'device-id',
        phaseLabel: 'Device Identification',
        title: 'UX401 identified on job',
        guidedInstructions: 'Confirm the UX401 display is listed on the work order and the replacement unit is present.',
        quickCheckpoint: 'UX401 confirmed on work order.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX401' },
        displayOrder: 32,
      },

      // ========== 4. V400M Replacement ==========
      {
        id: 'v400m-identify-lane',
        phaseId: 'v400m',
        phaseLabel: 'V400M Replacement',
        title: 'Identify the correct lane',
        guidedInstructions:
          'Match the work order lane assignment to the physical stall. Verify stall signage and lane numbering before touching any equipment.',
        quickCheckpoint: 'Correct lane identified and verified.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'V400M' },
        displayOrder: 40,
      },
      {
        id: 'v400m-power-down',
        phaseId: 'v400m',
        phaseLabel: 'V400M Replacement',
        title: 'Power down and disconnect existing V400M',
        guidedInstructions:
          'Safely power down the existing V400M. Disconnect cables while preserving lane order and cable labeling. Do not force connectors.',
        quickCheckpoint: 'Existing V400M powered down and disconnected safely.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'V400M' },
        displayOrder: 41,
      },
      {
        id: 'v400m-install-replacement',
        phaseId: 'v400m',
        phaseLabel: 'V400M Replacement',
        title: 'Install the replacement V400M',
        guidedInstructions:
          'Mount the replacement V400M in the same position and orientation as the original. Use existing hardware where possible.',
        quickCheckpoint: 'Replacement V400M installed in correct position.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'V400M' },
        displayOrder: 42,
      },
      {
        id: 'v400m-restore-power',
        phaseId: 'v400m',
        phaseLabel: 'V400M Replacement',
        title: 'Restore power in the required lane order',
        guidedInstructions:
          'Reconnect power and data cables in the lane order specified on the work order. Verify each connection is seated fully before moving to the next lane.',
        quickCheckpoint: 'Power restored in correct lane order.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'V400M' },
        displayOrder: 43,
      },
      {
        id: 'v400m-validate-lane',
        phaseId: 'v400m',
        phaseLabel: 'V400M Replacement',
        title: 'Validate the lane assignment',
        guidedInstructions:
          'Confirm the replacement V400M is assigned to the correct lane/stall in the system. Check lane signage matches the terminal configuration.',
        quickCheckpoint: 'Lane assignment validated.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'V400M' },
        displayOrder: 44,
      },
      {
        id: 'v400m-connect-wifi',
        phaseId: 'v400m',
        phaseLabel: 'V400M Replacement',
        title: 'Connect to Sonic Wi-Fi if required',
        guidedInstructions:
          'If the work order specifies Wi-Fi connection for downloads or activation, connect the device to the Sonic network. Do not record or share Wi-Fi credentials in this app.',
        quickCheckpoint: 'Wi-Fi connected if work order requires it.',
        classification: 'conditional',
        condition: { type: 'job_field_equals', field: 'notes', value: 'wifi-required' },
        displayOrder: 45,
      },
      {
        id: 'v400m-capture-serial',
        phaseId: 'v400m',
        phaseLabel: 'V400M Replacement',
        title: 'Capture the replacement device serial number',
        guidedInstructions:
          'Record the serial number of the newly installed V400M. This is required for closeout and inventory custody.',
        quickCheckpoint: 'Replacement V400M serial captured.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'V400M' },
        displayOrder: 46,
        equipmentRequirements: [
          {
            id: 'v400m-new-serial',
            label: 'V400M replacement serial',
            deviceModel: 'V400M',
            quantity: 1,
            serialRequirement: 'new',
            classification: 'required',
            visitScope: 'any_visit',
          },
        ],
      },
      {
        id: 'v400m-verify-downloads',
        phaseId: 'v400m',
        phaseLabel: 'V400M Replacement',
        title: 'Verify downloads and status',
        guidedInstructions:
          'Allow the device to complete any required firmware, application, or configuration downloads. Confirm status indicators show the device is online and ready before leaving the stall.',
        quickCheckpoint: 'Downloads complete and status indicators normal.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'V400M' },
        displayOrder: 47,
      },
      {
        id: 'v400m-help-desk-verify',
        phaseId: 'v400m',
        phaseLabel: 'V400M Replacement',
        title: 'Obtain Verifone Help Desk verification when required',
        guidedInstructions:
          'If the work order requires Help Desk sign-off, contact Verifone support and obtain verbal or ticket confirmation that the replacement is recognized in their system. Record the case reference.',
        quickCheckpoint: 'Help Desk verification obtained if required.',
        classification: 'conditional',
        condition: { type: 'job_field_equals', field: 'notes', value: 'verifone-verify-required' },
        displayOrder: 48,
        supportEscalations: [
          {
            id: 'v400m-help-desk-case',
            escalationLabel: 'Verifone Help Desk verification case',
            contactRoleType: 'technical_support',
            instructions: 'Contact Verifone Help Desk for replacement verification. Use work-order-supplied contact details.',
            referenceNumberRequired: true,
            conditional: true,
            condition: { type: 'job_field_equals', field: 'notes', value: 'verifone-verify-required' },
          },
        ],
      },
      {
        id: 'v400m-manager-test',
        phaseId: 'v400m',
        phaseLabel: 'V400M Replacement',
        title: 'Manager performs test order / payment transaction',
        guidedInstructions:
          'Ask the store manager to perform a test order and payment transaction on the replacement V400M. Confirm the transaction processes correctly and prints or records a receipt.',
        quickCheckpoint: 'Manager test transaction completed successfully.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'V400M' },
        displayOrder: 49,
        testingRequirements: [
          {
            id: 'v400m-manager-payment-test',
            label: 'Manager test order / payment',
            validationType: 'manager_customer_verification',
            classification: 'required',
            instructions: 'Manager performs a real test order and payment on the replacement V400M.',
          },
        ],
      },

      // ========== 5. UX Pre-Removal Documentation ==========
      {
        id: 'ux301-front-photo',
        phaseId: 'ux-pre-removal',
        phaseLabel: 'UX Pre-Removal Documentation',
        title: 'UX301 front photo',
        guidedInstructions: 'Capture a clear front-facing photo of the existing UX301 before deinstallation.',
        quickCheckpoint: 'UX301 front photo captured.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        displayOrder: 50,
        proofRequirements: [
          {
            id: 'ux301-front-photo-proof',
            label: 'UX301 front photo',
            proofType: 'photo',
            classification: 'required',
            instructions: 'Capture a clear front-facing photo of the existing UX301 before deinstallation.',
            visitScope: 'any_visit',
            minimumCount: 1,
          },
        ],
      },
      {
        id: 'ux301-back-photo',
        phaseId: 'ux-pre-removal',
        phaseLabel: 'UX Pre-Removal Documentation',
        title: 'UX301 back photo',
        guidedInstructions: 'Capture a clear back-facing photo of the existing UX301 before deinstallation.',
        quickCheckpoint: 'UX301 back photo captured.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        displayOrder: 51,
        proofRequirements: [
          {
            id: 'ux301-back-photo-proof',
            label: 'UX301 back photo',
            proofType: 'photo',
            classification: 'required',
            instructions: 'Capture a clear back-facing photo of the existing UX301 before deinstallation.',
            visitScope: 'any_visit',
            minimumCount: 1,
          },
        ],
      },
      {
        id: 'ux301-damage-photo',
        phaseId: 'ux-pre-removal',
        phaseLabel: 'UX Pre-Removal Documentation',
        title: 'UX301 existing damage documentation',
        guidedInstructions:
          'Photograph any visible damage, wear, or environmental issues on the existing UX301 and surrounding stall before deinstallation.',
        quickCheckpoint: 'UX301 damage documented.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        displayOrder: 52,
        proofRequirements: [
          {
            id: 'ux301-damage-photo-proof',
            label: 'UX301 damage documentation',
            proofType: 'photo',
            classification: 'required',
            instructions: 'Photograph any visible damage on the existing UX301 and surrounding stall.',
            visitScope: 'any_visit',
            minimumCount: 1,
          },
        ],
      },
      {
        id: 'ux401-front-photo',
        phaseId: 'ux-pre-removal',
        phaseLabel: 'UX Pre-Removal Documentation',
        title: 'UX401 front photo',
        guidedInstructions: 'Capture a clear front-facing photo of the existing UX401 before deinstallation.',
        quickCheckpoint: 'UX401 front photo captured.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX401' },
        displayOrder: 53,
        proofRequirements: [
          {
            id: 'ux401-front-photo-proof',
            label: 'UX401 front photo',
            proofType: 'photo',
            classification: 'required',
            instructions: 'Capture a clear front-facing photo of the existing UX401 before deinstallation.',
            visitScope: 'any_visit',
            minimumCount: 1,
          },
        ],
      },
      {
        id: 'ux401-back-photo',
        phaseId: 'ux-pre-removal',
        phaseLabel: 'UX Pre-Removal Documentation',
        title: 'UX401 back photo',
        guidedInstructions: 'Capture a clear back-facing photo of the existing UX401 before deinstallation.',
        quickCheckpoint: 'UX401 back photo captured.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX401' },
        displayOrder: 54,
        proofRequirements: [
          {
            id: 'ux401-back-photo-proof',
            label: 'UX401 back photo',
            proofType: 'photo',
            classification: 'required',
            instructions: 'Capture a clear back-facing photo of the existing UX401 before deinstallation.',
            visitScope: 'any_visit',
            minimumCount: 1,
          },
        ],
      },
      {
        id: 'ux401-damage-photo',
        phaseId: 'ux-pre-removal',
        phaseLabel: 'UX Pre-Removal Documentation',
        title: 'UX401 existing damage documentation',
        guidedInstructions:
          'Photograph any visible damage, wear, or environmental issues on the existing UX401 and surrounding stall before deinstallation.',
        quickCheckpoint: 'UX401 damage documented.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX401' },
        displayOrder: 55,
        proofRequirements: [
          {
            id: 'ux401-damage-photo-proof',
            label: 'UX401 damage documentation',
            proofType: 'photo',
            classification: 'required',
            instructions: 'Photograph any visible damage on the existing UX401 and surrounding stall.',
            visitScope: 'any_visit',
            minimumCount: 1,
          },
        ],
      },
      {
        id: 'ux-power-cords',
        phaseId: 'ux-pre-removal',
        phaseLabel: 'UX Pre-Removal Documentation',
        title: 'Identify and mark power cords',
        guidedInstructions:
          'Before disconnecting anything, identify every power cord routed to the UX displays. Mark or label each cord so reinstallation follows the original routing.',
        quickCheckpoint: 'Power cords identified and marked.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        displayOrder: 56,
      },
      {
        id: 'ux-cable-photos',
        phaseId: 'ux-pre-removal',
        phaseLabel: 'UX Pre-Removal Documentation',
        title: 'Capture cable and grounding reference photos',
        guidedInstructions:
          'Photograph the cable routing, antenna placement, and grounding strap position before disconnecting anything. These photos are required for correct reassembly.',
        quickCheckpoint: 'Cable and grounding reference photos captured.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        displayOrder: 57,
        proofRequirements: [
          {
            id: 'ux-cable-reference-photo',
            label: 'Cable and grounding reference photo',
            proofType: 'photo',
            classification: 'required',
            instructions: 'Photograph cable routing, antenna placement, and grounding strap position before disconnecting.',
            visitScope: 'any_visit',
            minimumCount: 1,
          },
        ],
      },
      {
        id: 'ux-label-cables',
        phaseId: 'ux-pre-removal',
        phaseLabel: 'UX Pre-Removal Documentation',
        title: 'Label and reference cable positions',
        guidedInstructions:
          'Use temporary labels or tape to mark where each cable connects. Note antenna ports, grounding points, and data cable orientation so reinstallation is exact.',
        quickCheckpoint: 'Cable positions labeled and referenced.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        displayOrder: 58,
      },
      {
        id: 'ux301-capture-old-serial',
        phaseId: 'ux-pre-removal',
        phaseLabel: 'UX Pre-Removal Documentation',
        title: 'Capture old UX301 serial number',
        guidedInstructions:
          'Record the serial number of the existing UX301 before removing it. This is required for inventory custody and closeout.',
        quickCheckpoint: 'Old UX301 serial captured.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        displayOrder: 59,
        equipmentRequirements: [
          {
            id: 'ux301-old-serial',
            label: 'Old UX301 serial',
            deviceModel: 'UX301',
            quantity: 1,
            serialRequirement: 'old',
            trackRemovedEquipment: true,
            classification: 'required',
            visitScope: 'any_visit',
          },
        ],
      },
      {
        id: 'ux401-capture-old-serial',
        phaseId: 'ux-pre-removal',
        phaseLabel: 'UX Pre-Removal Documentation',
        title: 'Capture old UX401 serial number',
        guidedInstructions:
          'Record the serial number of the existing UX401 before removing it. This is required for inventory custody and closeout.',
        quickCheckpoint: 'Old UX401 serial captured.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX401' },
        displayOrder: 60,
        equipmentRequirements: [
          {
            id: 'ux401-old-serial',
            label: 'Old UX401 serial',
            deviceModel: 'UX401',
            quantity: 1,
            serialRequirement: 'old',
            trackRemovedEquipment: true,
            classification: 'required',
            visitScope: 'any_visit',
          },
        ],
      },

      // ========== 6. UX301 Removal ==========
      {
        id: 'ux301-unlock-doors',
        phaseId: 'ux301-removal',
        phaseLabel: 'UX301 Removal',
        title: 'Unlock and open the menu doors',
        guidedInstructions:
          'Unlock and open the menu enclosure doors to gain access to the UX301. Support the doors so they do not swing freely and damage the plexiglass or hardware.',
        quickCheckpoint: 'Menu doors unlocked and secured open.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        displayOrder: 70,
      },
      {
        id: 'ux301-remove-signage',
        phaseId: 'ux301-removal',
        phaseLabel: 'UX301 Removal',
        title: 'Remove signage and back lightboard if required',
        guidedInstructions:
          'If signage or a back lightboard blocks access to the UX301 mounting hardware, carefully remove and set it aside in a protected location.',
        quickCheckpoint: 'Signage/lightboard removed if blocking access.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        displayOrder: 71,
      },
      {
        id: 'ux301-mark-disconnect-power',
        phaseId: 'ux301-removal',
        phaseLabel: 'UX301 Removal',
        title: 'Mark and disconnect power appropriately',
        guidedInstructions:
          'Power down the UX301 at the appropriate breaker or switch. Mark the power cable and disconnect it before touching data cables.',
        quickCheckpoint: 'Power marked and disconnected safely.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        displayOrder: 72,
      },
      {
        id: 'ux301-document-antenna',
        phaseId: 'ux301-removal',
        phaseLabel: 'UX301 Removal',
        title: 'Document antenna and cable placement before disconnecting',
        guidedInstructions:
          'Before removing antennas or data cables, take a final reference photo showing exact placement and orientation. This is required for correct reinstallation.',
        quickCheckpoint: 'Antenna and cable placement documented.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        displayOrder: 73,
        proofRequirements: [
          {
            id: 'ux301-antenna-photo',
            label: 'UX301 antenna placement photo',
            proofType: 'photo',
            classification: 'required',
            instructions: 'Photo showing exact antenna and cable placement before disconnecting UX301.',
            visitScope: 'any_visit',
            minimumCount: 1,
          },
        ],
      },
      {
        id: 'ux301-remove-first',
        phaseId: 'ux301-removal',
        phaseLabel: 'UX301 Removal',
        title: 'Remove UX301 first to gain access to UX401',
        guidedInstructions:
          'Where the stall layout requires it, remove the UX301 first to create clearance for the UX401 behind it. Move slowly and avoid pulling cables through tight openings.',
        quickCheckpoint: 'UX301 removed first where required.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        warningText: 'UX301 is removed first where required to gain access to UX401.',
        displayOrder: 74,
      },
      {
        id: 'ux301-preserve-grounding',
        phaseId: 'ux301-removal',
        phaseLabel: 'UX301 Removal',
        title: 'Preserve grounding hardware and grounding strap',
        guidedInstructions:
          'The grounding strap must remain present and must be correctly reattached during installation. Do not cut, discard, or damage the grounding strap. Photograph the grounding connection before and after work.',
        quickCheckpoint: 'Grounding strap preserved and documented.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        warningText: 'CRITICAL: The grounding strap must remain present and must be correctly reattached during installation.',
        displayOrder: 75,
        proofRequirements: [
          {
            id: 'ux301-grounding-photo',
            label: 'UX301 grounding connection photo',
            proofType: 'photo',
            classification: 'required',
            instructions: 'Photograph the grounding strap connection before removal and after reinstallation.',
            visitScope: 'any_visit',
            minimumCount: 1,
          },
        ],
      },
      {
        id: 'ux301-preserve-cable-orientation',
        phaseId: 'ux301-removal',
        phaseLabel: 'UX301 Removal',
        title: 'Preserve directional cable routing and orientation',
        guidedInstructions:
          'Note the direction and bend radius of every cable before removal. Reinstall cables in the same orientation to avoid pinching, kinking, or interference with the door mechanism.',
        quickCheckpoint: 'Cable routing orientation preserved.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        warningText: 'Preserve directional cable routing / orientation.',
        displayOrder: 76,
      },
      {
        id: 'ux301-protect-plexiglass',
        phaseId: 'ux301-removal',
        phaseLabel: 'UX301 Removal',
        title: 'Protect plexiglass and surrounding stall hardware',
        guidedInstructions:
          'Place padding or a protective cloth over the plexiglass and any painted surfaces before resting tools or removed parts against them. Scratches and dents are customer-owned damage.',
        quickCheckpoint: 'Plexiglass and stall hardware protected.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        warningText: 'Protect the plexiglass and surrounding stall hardware from damage.',
        displayOrder: 77,
      },

      // ========== 7. UX401 Removal ==========
      {
        id: 'ux401-remove-after-ux301',
        phaseId: 'ux401-removal',
        phaseLabel: 'UX401 Removal',
        title: 'Remove UX401 after UX301 clearance',
        guidedInstructions:
          'Once the UX301 is removed and clearance is available, proceed with UX401 deinstallation. Follow the same documentation, labeling, and grounding preservation practices.',
        quickCheckpoint: 'UX401 removed safely after UX301 clearance.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX401' },
        displayOrder: 80,
      },
      {
        id: 'ux401-preserve-grounding',
        phaseId: 'ux401-removal',
        phaseLabel: 'UX401 Removal',
        title: 'Preserve UX401 grounding hardware',
        guidedInstructions:
          'Preserve the UX401 grounding strap and hardware. Reattach it correctly during installation. Photograph the connection before removal and after reinstallation.',
        quickCheckpoint: 'UX401 grounding strap preserved.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX401' },
        warningText: 'CRITICAL: The grounding strap must remain present and must be correctly reattached during installation.',
        displayOrder: 81,
        proofRequirements: [
          {
            id: 'ux401-grounding-photo',
            label: 'UX401 grounding connection photo',
            proofType: 'photo',
            classification: 'required',
            instructions: 'Photograph the UX401 grounding strap connection before removal and after reinstallation.',
            visitScope: 'any_visit',
            minimumCount: 1,
          },
        ],
      },
      {
        id: 'ux401-preserve-cables',
        phaseId: 'ux401-removal',
        phaseLabel: 'UX401 Removal',
        title: 'Preserve UX401 cable routing and orientation',
        guidedInstructions:
          'Maintain the original cable routing and orientation for the UX401. Label each connection point before disconnecting.',
        quickCheckpoint: 'UX401 cable routing preserved.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX401' },
        warningText: 'Preserve directional cable routing / orientation.',
        displayOrder: 82,
      },

      // ========== 8. UX Installation ==========
      {
        id: 'ux-install-cables',
        phaseId: 'ux-install',
        phaseLabel: 'UX Installation',
        title: 'Reconnect cables in documented orientation',
        guidedInstructions:
          'Reconnect all data and power cables using the reference photos and labels from removal. Match the original orientation and bend radius exactly.',
        quickCheckpoint: 'Cables reconnected in documented orientation.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        displayOrder: 90,
      },
      {
        id: 'ux-install-antennas',
        phaseId: 'ux-install',
        phaseLabel: 'UX Installation',
        title: 'Reconnect antennas',
        guidedInstructions:
          'Reattach antennas to the same ports and in the same orientation captured in the reference photos. Do not overtighten.',
        quickCheckpoint: 'Antennas reconnected correctly.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        displayOrder: 91,
      },
      {
        id: 'ux-install-grounding',
        phaseId: 'ux-install',
        phaseLabel: 'UX Installation',
        title: 'Restore grounding strap',
        guidedInstructions:
          'Reattach the grounding strap exactly as photographed during removal. Verify metal-to-metal contact and secure the fastener. This is a safety-critical step.',
        quickCheckpoint: 'Grounding strap restored and verified.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        warningText: 'CRITICAL: Restore grounding strap — metal-to-metal contact must be verified.',
        displayOrder: 92,
      },
      {
        id: 'ux-install-power',
        phaseId: 'ux-install',
        phaseLabel: 'UX Installation',
        title: 'Restore power connections',
        guidedInstructions:
          'Reconnect power cables in the order documented during removal. Verify the breaker or switch is in the correct position before energizing.',
        quickCheckpoint: 'Power connections restored.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        displayOrder: 93,
      },
      {
        id: 'ux-install-panels',
        phaseId: 'ux-install',
        phaseLabel: 'UX Installation',
        title: 'Reinstall signage, lightboard, and access panels',
        guidedInstructions:
          'Reinstall any removed signage, lightboard, or access panels. Confirm they are seated squarely and fastened without over-torquing.',
        quickCheckpoint: 'Signage, lightboard, and panels reinstalled.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        displayOrder: 94,
      },
      {
        id: 'ux-install-secure',
        phaseId: 'ux-install',
        phaseLabel: 'UX Installation',
        title: 'Verify physical installation is secure',
        guidedInstructions:
          'Gently test the installed display and surrounding hardware for looseness or vibration. Tighten fasteners as needed. Confirm the door closes and latches correctly.',
        quickCheckpoint: 'Physical installation verified secure.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        displayOrder: 95,
      },

      // ========== 9. UX301 Configuration ==========
      {
        id: 'ux301-admin-access',
        phaseId: 'ux301-config',
        phaseLabel: 'UX301 Configuration',
        title: 'Access Windows administrative functions',
        guidedInstructions:
          'Access the Windows administrative interface on the replacement UX301 as required by the work order. Do not use unauthorized credentials.',
        quickCheckpoint: 'Windows admin access obtained as required.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        displayOrder: 100,
      },
      {
        id: 'ux301-run-stallsetup',
        phaseId: 'ux301-config',
        phaseLabel: 'UX301 Configuration',
        title: 'Run StallSetup.exe',
        guidedInstructions:
          'Launch StallSetup.exe on the replacement UX301. Follow the on-screen prompts. If the setup file is missing, use the setup file supplied by Solugenix.',
        quickCheckpoint: 'StallSetup.exe launched.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        displayOrder: 101,
      },
      {
        id: 'ux301-enter-store',
        phaseId: 'ux301-config',
        phaseLabel: 'UX301 Configuration',
        title: 'Enter required store number',
        guidedInstructions:
          'Enter the store number assigned to this Sonic location when prompted by StallSetup. Use the value provided on the work order or by site staff.',
        quickCheckpoint: 'Store number entered.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        displayOrder: 102,
      },
      {
        id: 'ux301-enter-stall',
        phaseId: 'ux301-config',
        phaseLabel: 'UX301 Configuration',
        title: 'Enter required stall number',
        guidedInstructions:
          'Enter the stall number for this lane when prompted by StallSetup. Use the value provided on the work order or by site staff.',
        quickCheckpoint: 'Stall number entered.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        displayOrder: 103,
      },
      {
        id: 'ux301-complete-setup',
        phaseId: 'ux301-config',
        phaseLabel: 'UX301 Configuration',
        title: 'Complete setup',
        guidedInstructions:
          'Finish the remaining StallSetup prompts. Do not skip network, display, or payment configuration steps unless directed by the work order.',
        quickCheckpoint: 'Setup completed.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        displayOrder: 104,
      },
      {
        id: 'ux301-reboot',
        phaseId: 'ux301-config',
        phaseLabel: 'UX301 Configuration',
        title: 'Reboot when required',
        guidedInstructions:
          'If StallSetup or the work order requires a reboot, restart the UX301 and confirm it boots to the expected screen.',
        quickCheckpoint: 'Reboot completed if required.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        displayOrder: 105,
      },
      {
        id: 'ux301-verify-serial',
        phaseId: 'ux301-config',
        phaseLabel: 'UX301 Configuration',
        title: 'Capture and verify new UX301 serial',
        guidedInstructions:
          'Record the serial number of the newly installed UX301. Verify it matches the replacement unit listed on the work order.',
        quickCheckpoint: 'New UX301 serial captured and verified.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        displayOrder: 106,
        equipmentRequirements: [
          {
            id: 'ux301-new-serial',
            label: 'New UX301 serial',
            deviceModel: 'UX301',
            quantity: 1,
            serialRequirement: 'new',
            classification: 'required',
            visitScope: 'any_visit',
          },
        ],
      },
      {
        id: 'ux301-missing-setup-file',
        phaseId: 'ux301-config',
        phaseLabel: 'UX301 Configuration',
        title: 'Missing setup file — use Solugenix-supplied file',
        guidedInstructions:
          'If StallSetup.exe or the required configuration files are missing on the replacement device, use the setup file supplied by Solugenix. Do not download from unverified sources.',
        quickCheckpoint: 'Solugenix setup file used if original missing.',
        classification: 'reference',
        displayOrder: 107,
      },

      // ========== 10. Testing ==========
      {
        id: 'test-device-powers-on',
        phaseId: 'testing',
        phaseLabel: 'Testing',
        title: 'Device powers on',
        guidedInstructions:
          'Power on every replaced or reinstalled device. Confirm the screen illuminates, the boot sequence runs, and no error codes are displayed.',
        quickCheckpoint: 'All devices power on successfully.',
        classification: 'required',
        displayOrder: 110,
        testingRequirements: [
          {
            id: 'test-power-on',
            label: 'Device powers on',
            validationType: 'visual_verification',
            classification: 'required',
            instructions: 'Confirm the device boots and displays the expected startup screen.',
          },
        ],
      },
      {
        id: 'test-downloads-complete',
        phaseId: 'testing',
        phaseLabel: 'Testing',
        title: 'Expected downloads and status complete',
        guidedInstructions:
          'Wait for all required firmware, application, or configuration downloads to finish. Confirm status indicators show the device is online and fully configured.',
        quickCheckpoint: 'Downloads and status indicators complete.',
        classification: 'required',
        displayOrder: 111,
        testingRequirements: [
          {
            id: 'test-downloads-status',
            label: 'Downloads and status complete',
            validationType: 'connectivity_test',
            classification: 'required',
            instructions: 'Confirm all required downloads finish and status shows online.',
          },
        ],
      },
      {
        id: 'test-lane-correct',
        phaseId: 'testing',
        phaseLabel: 'Testing',
        title: 'Lane and stall assignment correct',
        guidedInstructions:
          'Verify the device reports the correct lane and stall number in the POS or management interface. Cross-check against the work order.',
        quickCheckpoint: 'Lane/stall assignment verified correct.',
        classification: 'required',
        displayOrder: 112,
        testingRequirements: [
          {
            id: 'test-lane-assignment',
            label: 'Lane / stall assignment correct',
            validationType: 'visual_verification',
            classification: 'required',
            instructions: 'Verify the device shows the correct lane and stall assignment.',
          },
        ],
      },
      {
        id: 'test-help-desk-verify',
        phaseId: 'testing',
        phaseLabel: 'Testing',
        title: 'Help Desk verification when applicable',
        guidedInstructions:
          'If the work order requires Help Desk verification of test results, contact Verifone support and confirm the device is reporting correctly. Record the case reference.',
        quickCheckpoint: 'Help Desk verification completed if required.',
        classification: 'conditional',
        condition: { type: 'job_field_equals', field: 'notes', value: 'verifone-verify-required' },
        displayOrder: 113,
        supportEscalations: [
          {
            id: 'test-help-desk-case',
            escalationLabel: 'Verifone Help Desk test verification',
            contactRoleType: 'technical_support',
            instructions: 'Contact Verifone Help Desk for test-result verification. Use work-order-supplied contact details.',
            referenceNumberRequired: true,
            conditional: true,
            condition: { type: 'job_field_equals', field: 'notes', value: 'verifone-verify-required' },
          },
        ],
      },
      {
        id: 'test-manager-transaction',
        phaseId: 'testing',
        phaseLabel: 'Testing',
        title: 'Manager performs test order and payment transaction',
        guidedInstructions:
          'Ask the store manager to place a test order and complete a payment transaction on the newly installed device. Confirm the transaction is accepted and a receipt is produced.',
        quickCheckpoint: 'Manager test order and payment successful.',
        classification: 'required',
        displayOrder: 114,
        testingRequirements: [
          {
            id: 'test-manager-payment',
            label: 'Manager test order / payment transaction',
            validationType: 'manager_customer_verification',
            classification: 'required',
            instructions: 'Manager places a test order and completes payment on the replaced device.',
          },
        ],
      },
      {
        id: 'test-final-functionality',
        phaseId: 'testing',
        phaseLabel: 'Testing',
        title: 'Final device functionality confirmed',
        guidedInstructions:
          'Run a final visual and functional check on every installed or replaced device. Confirm touchscreen response, card reader insertion, receipt printing, and network connectivity.',
        quickCheckpoint: 'Final functionality confirmed on all devices.',
        classification: 'required',
        displayOrder: 115,
        testingRequirements: [
          {
            id: 'test-final-functionality-check',
            label: 'Final device functionality',
            validationType: 'visual_verification',
            classification: 'required',
            instructions: 'Confirm touchscreen, card reader, receipt, and network all function correctly.',
          },
        ],
      },

      // ========== 11. Troubleshooting / Escalation ==========
      {
        id: 'ts-install-issues',
        phaseId: 'troubleshooting',
        phaseLabel: 'Troubleshooting / Escalation',
        title: 'Installation issues reference',
        guidedInstructions:
          'If a device does not seat correctly, a cable does not reach, or mounting hardware is missing, stop work and document the issue. Do not force parts. Escalate to Verifone Help Desk using the work order contact details.',
        quickCheckpoint: 'Installation issue documented and escalated if needed.',
        classification: 'reference',
        displayOrder: 120,
      },
      {
        id: 'ts-wifi-issues',
        phaseId: 'troubleshooting',
        phaseLabel: 'Troubleshooting / Escalation',
        title: 'Wi-Fi issues reference',
        guidedInstructions:
          'If the device cannot connect to the Sonic network, verify antenna placement, check for nearby interference, and confirm the network name with the manager. Do not alter router settings. Escalate persistent issues to Verifone Help Desk.',
        quickCheckpoint: 'Wi-Fi issue troubleshooting steps reviewed.',
        classification: 'reference',
        displayOrder: 121,
      },
      {
        id: 'ts-power-issues',
        phaseId: 'troubleshooting',
        phaseLabel: 'Troubleshooting / Escalation',
        title: 'Power issues reference',
        guidedInstructions:
          'If a device does not power on, verify breaker position, cable seating, and outlet voltage with the manager. Do not perform electrical repairs beyond cable reseating. Escalate to Verifone Help Desk.',
        quickCheckpoint: 'Power issue troubleshooting steps reviewed.',
        classification: 'reference',
        displayOrder: 122,
      },
      {
        id: 'ts-order-test-issues',
        phaseId: 'troubleshooting',
        phaseLabel: 'Troubleshooting / Escalation',
        title: 'Order and test transaction issues reference',
        guidedInstructions:
          'If the manager test order fails, verify device lane assignment, network status, and payment configuration. Record the exact error. Escalate to Verifone Help Desk if the issue is device-side.',
        quickCheckpoint: 'Order/test issue troubleshooting steps reviewed.',
        classification: 'reference',
        displayOrder: 123,
      },
      {
        id: 'ts-download-issues',
        phaseId: 'troubleshooting',
        phaseLabel: 'Troubleshooting / Escalation',
        title: 'Download and status issues reference',
        guidedInstructions:
          'If downloads stall or status shows offline, verify network connectivity, wait additional time, and power cycle once if safe. Record the status screenshot. Escalate to Verifone Help Desk if the issue persists.',
        quickCheckpoint: 'Download/status issue troubleshooting steps reviewed.',
        classification: 'reference',
        displayOrder: 124,
      },
      {
        id: 'ts-escalate-verifone',
        phaseId: 'troubleshooting',
        phaseLabel: 'Troubleshooting / Escalation',
        title: 'Escalate to Verifone Help Desk',
        guidedInstructions:
          'When a device-side issue cannot be resolved with the available site information, escalate to Verifone Help Desk. Provide the site name, work order number, device type, serial numbers, and a description of the issue. Use only the contact details supplied on the work order.',
        quickCheckpoint: 'Escalation criteria and required info reviewed.',
        classification: 'reference',
        displayOrder: 125,
        supportEscalations: [
          {
            id: 'ts-verifone-escalation-case',
            escalationLabel: 'Verifone Help Desk escalation',
            contactRoleType: 'technical_support',
            instructions: 'Escalate to Verifone Help Desk using work-order-supplied contact details. Provide site, work order, device type, serials, and issue description.',
            referenceNumberRequired: true,
          },
        ],
      },

      // ========== 12. Closeout / Returns ==========
      {
        id: 'closeout-removed-equipment',
        phaseId: 'closeout',
        phaseLabel: 'Closeout / Returns',
        title: 'Record removed equipment in inventory custody',
        guidedInstructions:
          'Record every removed device in Inventory Custody with its old serial number, part number if known, and removal event. Removed equipment is not the same as returned equipment.',
        quickCheckpoint: 'Removed equipment recorded in custody.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        displayOrder: 130,
        equipmentRequirements: [
          {
            id: 'closeout-ux301-removed',
            label: 'Removed UX301 recorded',
            deviceModel: 'UX301',
            quantity: 1,
            serialRequirement: 'old',
            trackRemovedEquipment: true,
            returnRequired: true,
            classification: 'required',
            visitScope: 'any_visit',
          },
        ],
      },
      {
        id: 'closeout-return-obligations',
        phaseId: 'closeout',
        phaseLabel: 'Closeout / Returns',
        title: 'Satisfy return obligations',
        guidedInstructions:
          'If the work order requires equipment return, record the return in Inventory Custody with a receipt number and tracking number. The job remains in Work Complete — Pending Closeout until the return obligation is satisfied.',
        quickCheckpoint: 'Return obligation satisfied with receipt and tracking.',
        classification: 'conditional',
        condition: { type: 'device_type_equals', deviceType: 'UX301' },
        displayOrder: 131,
        equipmentRequirements: [
          {
            id: 'closeout-ux301-return',
            label: 'Returned UX301 with receipt and tracking',
            deviceModel: 'UX301',
            quantity: 1,
            serialRequirement: 'old',
            trackRemovedEquipment: true,
            returnRequired: true,
            classification: 'required',
            visitScope: 'any_visit',
          },
        ],
      },
    ],
  },
];
