import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, Camera, Check, ChevronDown, ChevronUp, FileVideo, Image as ImageIcon, Loader2, MapPin, Navigation, RotateCcw, Trash2, X } from 'lucide-react';
import type { Job } from '../../types';
import { JobTransitSection } from '../../components/transit/JobTransitSection';
import { isTransitApiEnabled } from '../../services/transit';
import { createPreviewSummary } from './summaryService';
import { extractPreviewFrames, validatePreviewRecording } from './frameExtraction';
import { deleteGuide, deleteMedia, estimateAvailableStorage, getMedia, getPreviewGuide, saveMedia, savePreviewGuide } from './storage';
import type { JobPreviewGuide, JobPreviewSummary, PreparationState, PreviewPage, PreviewRequirement } from './types';
import { effectiveConfirmationMode, incompleteRequiredRequirements } from './readiness';

interface Props { job: Job; navLink: string; transitOrigin?: { latitude: number; longitude: number }; onClose: () => void }
type View = 'home' | 'original' | 'reference' | 'select' | 'review' | 'prepare' | 'travel' | 'arrived' | 'storage';
const uid = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
const now = () => new Date().toISOString();

function emptyGuide(jobId: string): JobPreviewGuide {
  const createdAt = now();
  return { id: uid('guide'), jobId, status: 'empty', stage: 'no_preview', sourceType: 'screen_recording', pageIds: [], pages: [], preparation: [], extractionVersion: 1, createdAt, updatedAt: createdAt };
}

function MediaImage({ mediaRef, alt, className = '' }: { mediaRef: string; alt: string; className?: string }) {
  const [url, setUrl] = useState('');
  useEffect(() => { let live = true, objectUrl = ''; void getMedia(mediaRef).then(blob => { if (blob && live) { objectUrl = URL.createObjectURL(blob); setUrl(objectUrl); } }); return () => { live = false; if (objectUrl) URL.revokeObjectURL(objectUrl); }; }, [mediaRef]);
  return url ? <img src={url} alt={alt} className={className} /> : <div className={`animate-pulse bg-white/5 ${className}`} aria-label={`Loading ${alt}`} />;
}

function Section({ title, items }: { title: string; items: { id: string; text: string }[] }) {
  if (!items.length) return null;
  return <section><h3 className="text-xs font-black uppercase tracking-wider text-slate-400">{title}</h3><ul className="mt-2 space-y-2">{items.map(item => <li key={item.id} className="rounded-xl bg-white/[.04] px-3 py-2 text-sm text-slate-200">{item.text}</li>)}</ul></section>;
}

export default function PreviewGuideModal({ job, navLink, transitOrigin, onClose }: Props) {
  const [guide, setGuide] = useState<JobPreviewGuide>(() => getPreviewGuide(job.id) || emptyGuide(job.id));
  const [view, setView] = useState<View>(() => guide.stage === 'preparation' || guide.stage === 'ready_to_travel' ? 'prepare' : guide.stage === 'travel_planning' || guide.stage === 'traveling' ? 'travel' : guide.stage === 'arrived' || guide.stage === 'job_guide' ? 'arrived' : 'home');
  const [progress, setProgress] = useState(0); const [progressLabel, setProgressLabel] = useState('Preparing recording'); const [error, setError] = useState('');
  const abortRef = useRef<AbortController | null>(null); const fileRef = useRef<HTMLInputElement>(null); const addPageRef = useRef<HTMLInputElement>(null); const prepFileRef = useRef<HTMLInputElement>(null); const [activeRequirement, setActiveRequirement] = useState<string | null>(null);
  const includedPages = useMemo(() => guide.pages.filter(p => p.status === 'included').sort((a, b) => a.order - b.order), [guide.pages]);
  const removedPages = guide.pages.filter(p => p.status === 'removed'); const readingPages = view === 'reference' ? includedPages.filter(p => p.tags.includes('reference-image')) : includedPages;

  const persist = (next: JobPreviewGuide) => { savePreviewGuide(next); setGuide(next); };
  useEffect(() => { const escape = (e: KeyboardEvent) => e.key === 'Escape' && onClose(); window.addEventListener('keydown', escape); return () => window.removeEventListener('keydown', escape); }, [onClose]);

  const importRecording = async (file?: File) => {
    const validation = validatePreviewRecording(file); if (validation || !file) return setError(validation || 'Choose a recording.');
    setError(''); const estimate = await estimateAvailableStorage(); if (estimate.quota && estimate.usage && estimate.quota - estimate.usage < file.size * 1.4) return setError('This phone may not have enough free storage. Remove old preview media or trim the recording.');
    const controller = new AbortController(); abortRef.current = controller; setProgress(1); setProgressLabel('Preparing recording');
    persist({ ...guide, status: 'processing', stage: 'processing' });
    try {
      const videoRef = uid('video'); await saveMedia({ id: videoRef, jobId: job.id, kind: 'video', blob: file, createdAt: now() });
      const frames = await extractPreviewFrames(file, { signal: controller.signal, onProgress: (p, label) => { setProgress(p); setProgressLabel(label); } });
      const guideId = guide.id || uid('guide'); const pages: PreviewPage[] = [];
      for (let i = 0; i < frames.length; i++) {
        const pageId = uid('page'), imageRef = `${pageId}-full`, thumbnailRef = `${pageId}-thumb`;
        await saveMedia({ id: imageRef, jobId: job.id, kind: 'page', blob: frames[i].image, createdAt: now() });
        await saveMedia({ id: thumbnailRef, jobId: job.id, kind: 'thumbnail', blob: frames[i].thumbnail, createdAt: now() });
        pages.push({ id: pageId, guideId, order: i, imageRef, thumbnailRef, sourceTimeSeconds: frames[i].sourceTimeSeconds, status: 'included', selectedForSummary: false, tags: [] });
      }
      const next = { ...guide, id: guideId, status: 'ready' as const, stage: 'preview_ready' as const, sourceVideoRef: videoRef, pages, pageIds: pages.map(p => p.id), coverPageId: pages[0]?.id, extractionVersion: 1 };
      persist(next); setView('original');
    } catch (e) { const message = e instanceof DOMException && e.name === 'AbortError' ? 'Processing was cancelled. Your existing guide was not replaced.' : e instanceof Error ? e.message : 'The recording could not be processed.'; setError(message); persist({ ...guide, status: guide.pages.length ? 'ready' : 'failed', stage: guide.pages.length ? 'preview_ready' : 'no_preview' }); }
    finally { abortRef.current = null; setProgress(0); if (fileRef.current) fileRef.current.value = ''; }
  };

  const updatePage = (id: string, update: Partial<PreviewPage>) => persist({ ...guide, pages: guide.pages.map(p => p.id === id ? { ...p, ...update } : p) });
const addPage = async (file?: File) => {
    if (!file || !file.type.startsWith('image/')) return setError('Choose an image to add as a preview page.');
    const pageId = uid('page'), imageRef = pageId + '-full', thumbnailRef = pageId + '-thumb';
    try {
      await saveMedia({ id: imageRef, jobId: job.id, kind: 'page', blob: file, createdAt: now() });
      await saveMedia({ id: thumbnailRef, jobId: job.id, kind: 'thumbnail', blob: file, createdAt: now() });
      const page: PreviewPage = { id: pageId, guideId: guide.id, order: includedPages.length, imageRef, thumbnailRef, sourceTimeSeconds: -1, status: 'included', selectedForSummary: false, tags: [] };
      persist({ ...guide, pages: [...guide.pages, page], pageIds: [...guide.pageIds, pageId] });
    } catch { setError('That page could not be saved. Free device storage and try again.'); }
    finally { if (addPageRef.current) addPageRef.current.value = ''; }
  };
  const reorder = (id: string, direction: -1 | 1) => { const list = [...includedPages], index = list.findIndex(p => p.id === id), other = index + direction; if (other < 0 || other >= list.length) return; [list[index], list[other]] = [list[other], list[index]]; const orders = new Map(list.map((p, i) => [p.id, i])); persist({ ...guide, pages: guide.pages.map(p => orders.has(p.id) ? { ...p, order: orders.get(p.id)! } : p) }); };

  const summarize = async () => {
    setError(''); persist({ ...guide, stage: 'summary_processing' }); setProgress(15); setProgressLabel('Creating your quick summary');
    try { const summary = await createPreviewSummary(guide.pages); const next = { ...guide, summary, stage: 'summary_review' as const, status: 'needs_review' as const }; persist(next); setView('review'); }
    catch (e) { setError(e instanceof Error ? e.message : 'The quick summary could not be created.'); persist({ ...guide, stage: 'summary_selecting' }); }
    finally { setProgress(0); }
  };

  const changeSummary = (summary: JobPreviewSummary) => persist({ ...guide, summary });
  const reviewRequirement = (id: string, update?: Partial<PreviewRequirement>) => { if (!guide.summary) return; changeSummary({ ...guide.summary, beforeYouGo: update ? guide.summary.beforeYouGo.map(r => r.id === id ? { ...r, ...update } : r) : guide.summary.beforeYouGo.filter(r => r.id !== id) }); };
  const saveReviewedSummary = () => { if (!guide.summary) return; const summary = { ...guide.summary, reviewedByUser: true }; const preparation = summary.beforeYouGo.map(r => guide.preparation.find(p => p.requirementId === r.id) || { requirementId: r.id, status: 'incomplete' as const }); persist({ ...guide, summary, preparation, status: 'ready', stage: 'preparation', lastReviewedAt: now() }); setView('home'); };

  const setPrep = (requirementId: string, state: Partial<PreparationState>) => persist({ ...guide, stage: 'preparation', preparation: guide.preparation.map(p => p.requirementId === requirementId ? { ...p, ...state } : p) });
  const capturePreparationPhoto = async (file?: File) => { if (!file || !activeRequirement) return; if (!file.type.startsWith('image/')) return setError('Choose or take a photo.'); const ref = uid('prep'); try { await saveMedia({ id: ref, jobId: job.id, kind: 'preparation', blob: file, createdAt: now() }); const old = guide.preparation.find(p => p.requirementId === activeRequirement)?.photoRef; setPrep(activeRequirement, { status: 'complete', confirmedAt: now(), photoRef: ref }); if (old) void deleteMedia(old); } catch { setError('The photo could not be saved. Free device storage and try again.'); } finally { setActiveRequirement(null); if (prepFileRef.current) prepFileRef.current.value = ''; } };
  const requiredIncomplete = incompleteRequiredRequirements(guide.summary?.beforeYouGo || [], guide.preparation);
  const readyForTravel = !requiredIncomplete.length && !!guide.summary?.reviewedByUser;

  const header = (title: string, back?: View) => <div className="sticky top-0 z-10 flex items-center gap-2 border-b border-white/10 bg-[#111214]/95 px-3 py-3 backdrop-blur"><button className="flex h-11 w-11 items-center justify-center rounded-xl bg-white/5" onClick={() => back ? setView(back) : onClose()} aria-label={back ? 'Go back' : 'Close'}>{back ? <ArrowLeft /> : <X />}</button><div className="min-w-0 flex-1"><p className="truncate text-base font-black text-white">{title}</p><p className="truncate text-xs text-slate-400">{job.storeName}</p></div></div>;

  let body;
  if (progress) body = <><div className="space-y-4 p-5 text-center"><Loader2 className="mx-auto animate-spin text-cyan-400" size={36}/><h2 className="text-xl font-black">{progressLabel}</h2><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-cyan-500 transition-all" style={{ width: `${progress}%` }}/></div><p aria-live="polite" className="text-sm text-slate-400">{progress}% complete</p><button onClick={() => abortRef.current?.abort()} className="min-h-12 w-full rounded-xl border border-white/10 font-black">Cancel</button></div></>;
  else if (view === 'original' || view === 'reference') body = <><div className="space-y-4 p-3"><div className="rounded-xl border border-amber-500/20 bg-amber-500/10 p-3 text-xs text-amber-200">Use the original job app as the final source of truth while completing and submitting the job.</div>{readingPages.map((page, index) => <article key={page.id} className="overflow-hidden rounded-xl border border-white/10 bg-black"><MediaImage mediaRef={page.imageRef} alt={`Original preview page ${index + 1}`} className="h-auto w-full object-contain"/><div className="flex items-center gap-1 p-2"><span className="mr-auto text-xs text-slate-400">Page {index + 1} of {readingPages.length}</span><button onClick={() => persist({ ...guide, coverPageId: page.id })} aria-label="Choose cover page" className={guide.coverPageId === page.id ? "px-2 py-1 text-xs font-black text-cyan-400" : "px-2 py-1 text-xs font-black"}>Cover</button><button onClick={() => reorder(page.id, -1)} aria-label="Move page up" className="p-2"><ChevronUp/></button><button onClick={() => reorder(page.id, 1)} aria-label="Move page down" className="p-2"><ChevronDown/></button><button onClick={() => updatePage(page.id, { tags: page.tags.includes('reference-image') ? page.tags.filter(t => t !== 'reference-image') : [...page.tags, 'reference-image'] })} aria-label="Use as reference photo" className={`p-2 ${page.tags.includes('reference-image') ? 'text-cyan-400' : ''}`}><ImageIcon/></button><button onClick={() => updatePage(page.id, { status: 'removed' })} aria-label="Remove page" className="p-2 text-rose-400"><Trash2/></button></div></article>)}<button onClick={() => addPageRef.current?.click()} className="min-h-12 w-full rounded-xl border border-white/10 font-black">Add Frame</button><input ref={addPageRef} type="file" accept="image/*" className="hidden" onChange={e => void addPage(e.target.files?.[0])}/>{removedPages.length > 0 && <button onClick={() => persist({ ...guide, pages: guide.pages.map(p => ({ ...p, status: 'included' })) })} className="min-h-12 w-full rounded-xl border border-white/10 font-black"><RotateCcw className="mr-2 inline" size={18}/>Restore Removed Pages ({removedPages.length})</button>}<button onClick={() => { persist({ ...guide, stage: 'summary_selecting' }); setView('select'); }} className="min-h-12 w-full rounded-xl bg-cyan-600 font-black">Select Important Pages</button></div></>;
  else if (view === 'select') body = <><div className="space-y-4 p-4"><p className="text-sm text-slate-300">Select the pages with the most important instructions. Only selected preview pages will be processed.</p><div className="flex gap-2"><button onClick={() => persist({ ...guide, pages: guide.pages.map(p => p.status === 'included' ? { ...p, selectedForSummary: true } : p) })} className="min-h-11 flex-1 rounded-xl border border-white/10 font-bold">Select All</button><button onClick={() => persist({ ...guide, pages: guide.pages.map(p => ({ ...p, selectedForSummary: false })) })} className="min-h-11 flex-1 rounded-xl border border-white/10 font-bold">Clear</button></div><div className="grid grid-cols-2 gap-2">{includedPages.map((p, i) => <button key={p.id} onClick={() => updatePage(p.id, { selectedForSummary: !p.selectedForSummary })} className={`relative overflow-hidden rounded-xl border-2 ${p.selectedForSummary ? 'border-cyan-400' : 'border-white/10'}`} aria-pressed={p.selectedForSummary}><MediaImage mediaRef={p.thumbnailRef} alt={`Page ${i + 1}`} className="aspect-[9/16] w-full object-cover"/><span className="absolute bottom-1 left-1 rounded bg-black/70 px-2 py-1 text-xs">Page {i + 1}</span>{p.selectedForSummary && <Check className="absolute right-2 top-2 rounded-full bg-cyan-500 p-1"/>}</button>)}</div><button onClick={() => void summarize()} className="min-h-12 w-full rounded-xl bg-cyan-600 font-black">Start Summary</button></div></>;
  else if (view === 'review' && guide.summary) body = <><div className="space-y-4 p-4"><div className="rounded-xl bg-amber-500/10 p-3 text-xs text-amber-200">This guide was created from the preview recording. Confirm important requirements in the original job app.</div><h2 className="text-lg font-black">Before You Go</h2>{guide.summary.beforeYouGo.map(r => <div key={r.id} className="space-y-2 rounded-xl border border-white/10 p-3"><input value={r.text} onChange={e => reviewRequirement(r.id, { text: e.target.value })} className="w-full rounded-lg bg-white/5 p-2 text-sm" aria-label="Requirement text"/><div className="flex gap-2"><select value={r.confirmationMode} onChange={e => reviewRequirement(r.id, { confirmationMode: e.target.value as PreviewRequirement['confirmationMode'] })} className="min-h-11 flex-1 rounded-lg bg-[#222] p-2" aria-label="Confirmation type"><option value="photo">Photo</option><option value="one_tap">One tap</option><option value="review">Review</option><option value="none">None</option></select><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={r.required} onChange={e => reviewRequirement(r.id, { required: e.target.checked })}/>Required</label><button onClick={() => reviewRequirement(r.id)} className="p-2 text-rose-400" aria-label="Remove requirement"><Trash2/></button></div><button onClick={() => { const page = guide.pages.find(p => r.sourcePageIds.includes(p.id)); if (page) setView('original'); }} className="text-xs font-bold text-cyan-400">View Source Page</button></div>)}<Section title="What You'll Do" items={guide.summary.whatYouWillDo}/><Section title="Proof or Photos" items={guide.summary.proofRequirements}/><Section title="Important" items={guide.summary.warnings}/><button onClick={saveReviewedSummary} className="min-h-12 w-full rounded-xl bg-cyan-600 font-black">Save Preview Guide</button></div></>;
  else if (view === 'prepare' && guide.summary) body = <><div className="space-y-4 p-4"><p className="text-sm font-bold text-cyan-300">{guide.preparation.filter(p => p.status === 'complete').length} of {guide.summary.beforeYouGo.length} complete</p>{guide.summary.beforeYouGo.map(r => { const state = guide.preparation.find(p => p.requirementId === r.id); const mode = effectiveConfirmationMode(r); return <div key={r.id} className="rounded-xl border border-white/10 p-3"><div className="flex gap-2"><div className="flex-1"><h3 className="font-black">{r.text}</h3><p className="text-xs text-slate-400">{mode === 'photo' ? 'Photo required' : mode === 'one_tap' ? 'One-tap confirmation' : mode === 'review' ? 'Review required' : 'No confirmation required'}</p></div>{state?.status === 'complete' && <Check className="text-emerald-400"/>}</div><div className="mt-3">{mode === 'photo' ? <button onClick={() => { setActiveRequirement(r.id); prepFileRef.current?.click(); }} className="min-h-11 w-full rounded-xl bg-cyan-600 font-black"><Camera className="mr-2 inline" size={18}/>{state?.photoRef ? 'Retake Photo' : 'Take Proof Photo'}</button> : mode !== 'none' ? <button onClick={() => setPrep(r.id, state?.status === 'complete' ? { status: 'incomplete', confirmedAt: undefined } : { status: 'complete', confirmedAt: now() })} className="min-h-11 w-full rounded-xl bg-white/10 font-black">{state?.status === 'complete' ? 'Undo' : r.type === 'dress_code' ? "I'm Dressed Correctly" : 'Mark Reviewed'}</button> : null}</div><button onClick={() => { const page = guide.pages.find(p => r.sourcePageIds.includes(p.id)); if (page) setView('original'); }} className="mt-2 text-xs font-bold text-cyan-400">Why is this required?</button></div>})}<input ref={prepFileRef} type="file" accept="image/*" capture="environment" className="hidden" onChange={e => void capturePreparationPhoto(e.target.files?.[0])}/>{!readyForTravel && <p aria-live="polite" className="rounded-xl bg-amber-500/10 p-3 text-sm text-amber-200">{requiredIncomplete.length ? `${requiredIncomplete.length} required item${requiredIncomplete.length === 1 ? ' is' : 's are'} still incomplete: ${requiredIncomplete.map(r => r.text).join(', ')}.` : 'Review and save the summary first.'}</p>}{guide.stage === 'ready_to_travel' ? <div className="space-y-3 rounded-2xl bg-emerald-500/10 p-4 text-center"><h3 className="text-xl font-black text-emerald-300">You're Ready</h3><button onClick={() => { persist({ ...guide, stage: 'travel_planning' }); setView('travel'); }} className="min-h-14 w-full rounded-xl bg-emerald-600 font-black">I'm Ready — Plan My Trip</button></div> : <button disabled={!readyForTravel} onClick={() => persist({ ...guide, stage: 'ready_to_travel', completedAt: now() })} className="min-h-14 w-full rounded-xl bg-emerald-600 font-black disabled:cursor-not-allowed disabled:opacity-40">Complete Preparation</button>}</div></>;
  else if (view === 'travel') body = <><div className="space-y-4 p-4"><div className="text-center"><Navigation className="mx-auto text-emerald-400" size={38}/><h2 className="mt-2 text-xl font-black">You're ready to go</h2><p className="text-sm text-slate-400">{job.address || 'This job needs an address before a trip can be planned.'}</p></div>{!job.address ? <button className="min-h-12 w-full rounded-xl border border-white/10" onClick={onClose}>Return to Job</button> : <><a href={navLink} target="_blank" rel="noopener noreferrer" onClick={() => persist({ ...guide, stage: 'traveling', travelStartedAt: now() })} className="flex min-h-14 items-center justify-center rounded-xl bg-emerald-600 font-black">Start This Trip</a>{isTransitApiEnabled() && transitOrigin && <JobTransitSection job={job} origin={transitOrigin}/>}<a href={navLink} target="_blank" rel="noopener noreferrer" className="flex min-h-12 items-center justify-center rounded-xl border border-white/10 font-black">Compare Other Options</a><button onClick={() => { persist({ ...guide, stage: 'arrived', arrivedAt: now() }); setView('arrived'); }} className="min-h-12 w-full rounded-xl border border-cyan-500/30 text-cyan-300 font-black">I'm at the Store</button></>}</div></>;
  else if (view === 'arrived') body = <><div className="space-y-4 p-5 text-center"><MapPin className="mx-auto text-cyan-400" size={42}/><h2 className="text-2xl font-black">At the Store</h2><p className="text-slate-300">{guide.summary?.whatYouWillDo[0]?.text || 'Check in or review the first job instruction.'}</p><button onClick={() => persist({ ...guide, stage: 'job_guide' })} className="min-h-14 w-full rounded-xl bg-cyan-600 font-black">Start Job Guide</button><button onClick={() => setView('home')} className="min-h-12 w-full rounded-xl border border-white/10 font-black">View Preview</button><button onClick={onClose} className="min-h-12 w-full rounded-xl border border-white/10 font-black">Open Job Details</button></div></>;
  else if (view === 'storage') body = <><div className="space-y-3 p-4"><button disabled={!guide.sourceVideoRef} onClick={() => { if (!guide.sourceVideoRef || !confirm('Remove the original recording and keep extracted pages?')) return; void deleteMedia(guide.sourceVideoRef); persist({ ...guide, sourceVideoRef: undefined }); }} className="min-h-12 w-full rounded-xl border border-white/10 disabled:opacity-40">Remove Recording and Keep Pages</button><button onClick={() => { if (!confirm('Remove this Preview Guide and only its media?')) return; void deleteGuide(job.id).then(onClose); }} className="min-h-12 w-full rounded-xl border border-rose-500/30 text-rose-300">Remove Full Preview Guide</button></div></>;
  else body = <><div className="space-y-5 p-4">{guide.pages.length === 0 ? <><div className="rounded-2xl border border-dashed border-white/15 p-6 text-center"><FileVideo className="mx-auto text-cyan-400" size={38}/><h2 className="mt-3 text-xl font-black">No preview has been added for this job.</h2><p className="mt-2 text-sm text-slate-400">Import one slow screen recording of the original job preview.</p></div><button onClick={() => fileRef.current?.click()} className="min-h-14 w-full rounded-xl bg-cyan-600 font-black">Import Preview Recording</button></> : <><div><p className="text-xs font-black uppercase text-cyan-400">Preview ready</p><h2 className="text-2xl font-black">{guide.summary?.title || job.storeName}</h2><p className="text-sm text-slate-400">${job.pay.toFixed(2)} · About {guide.summary?.estimatedMinutes || job.estimatedMinutes} minutes</p></div>{guide.summary?.reviewedByUser ? <><Section title="Before You Go" items={guide.summary.beforeYouGo}/><Section title="What You'll Do" items={guide.summary.whatYouWillDo}/><Section title="Proof or Photos Likely Required" items={guide.summary.proofRequirements}/><Section title="Important" items={guide.summary.warnings}/><button onClick={() => setView('prepare')} className="min-h-14 w-full rounded-xl bg-cyan-600 font-black">Get Ready</button></> : <><p className="rounded-xl bg-white/[.04] p-3 text-sm">Your original preview pages are ready. Select the important pages to create a quick summary.</p><button onClick={() => setView('select')} className="min-h-14 w-full rounded-xl bg-cyan-600 font-black">Create Quick Summary</button></>}<button onClick={() => setView('original')} className="min-h-12 w-full rounded-xl border border-white/10 font-black">View Original Preview</button>{guide.pages.some(p => p.tags.includes('reference-image')) && <button onClick={() => setView('reference')} className="min-h-12 w-full rounded-xl border border-white/10 font-black">Reference Photos</button>}<button onClick={() => fileRef.current?.click()} className="min-h-12 w-full rounded-xl border border-white/10 font-black">Replace Recording</button><button onClick={() => setView('storage')} className="min-h-12 w-full rounded-xl border border-white/10 font-black">Manage Preview Storage</button></>}</div></>;

  return <div className="fixed inset-0 z-[100] bg-black/70 p-0 sm:p-4" role="dialog" aria-modal="true" aria-label="Job Preview Guide"><div className="mx-auto flex h-dvh w-full max-w-[480px] flex-col overflow-hidden bg-[#111214] text-white sm:h-[92dvh] sm:rounded-2xl sm:border sm:border-white/10">{header(view === 'original' ? 'Original Preview Capture' : view === 'reference' ? 'Reference Photos' : view === 'select' ? 'Select Important Pages' : view === 'review' ? 'Review Summary' : view === 'prepare' ? 'Get Ready' : view === 'travel' ? 'Plan My Trip' : view === 'arrived' ? 'At the Store' : view === 'storage' ? 'Manage Preview Storage' : 'Job Preview', view === 'home' ? undefined : 'home')}<div className="min-h-0 flex-1 overflow-y-auto">{error && <div className="m-3 rounded-xl border border-rose-500/20 bg-rose-500/10 p-3 text-sm text-rose-200" role="alert">{error}</div>}{body}</div><input ref={fileRef} type="file" accept="video/mp4,video/quicktime,video/*" className="hidden" onChange={e => void importRecording(e.target.files?.[0])}/></div></div>;
}
